### ISSUE TITLE
multiplay error

### ISSUE THREAD

**Issue by murakotaro4** [Shirkit/AdditionalPasteSettings#1]
This mod is very useful. Especially useful when putting restrictions on inserters from assembly machines. Thank you for a wonderful MOD.
I tried to spread this to my friends and I got a troubled problem.

An error like screenshot occurred when doing multiplay.
(to translate the screenshots in English, it means the following.)
Would you please remodel this MOD into MOD that can correspond to multiple play? .

![index](https://user-images.githubusercontent.com/7923699/41811845-46ee80a0-7752-11e8-988e-35722bedc49a.jpg)

can not join. The following MOD event handlers are different between you and the server. This indicates that the following MODs are not safe for multiplay save / load. (Please refer to the log file for details)

Best regard

**Comment by pa-philos** [comment]
Hey @murakotaro4 I do not know what's causing this, I didn't test my mod in Multiplayer.

Do you have a headless server running? Or are you connecting to a friend?

If you have some time available, I'd like to try to solve this issue. I'd need someone for me to test the multiplayer of this mod, maybe we can set up some time that we are both online so I can figure it out, because I can't test it on Multiplayer.

**Comment by murakotaro4** [comment]
This error occurred when I set up my own server and invite my friends.

I want to cooperate in your test.
I live in Tokyo. Time zone is +9 hours.

I have a discord account.
But i forget it now. I will tell you it later!

Best regards


2018年6月27日(水) 2:08 Shirkit <notifications@github.com>:

**Comment by pa-philos** [comment]
Ok, we'll try to arrange it, I live in -3 timezone, so it can be tricky to get a good time for us.

**Comment by murakotaro4** [comment]
I am sorry for late reply.
This is my Discord invitation.
[https://discord.gg/p64aGj](url) copy & paste your Discord app
I am busy this week so i hope you can arrange it on this weekend.
Can you arrange the schedule in Discord chat?

Thank you
